apiVersion: v1
kind: Service
metadata:
  name: sample-helm-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sample-helm-app
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
